Parchment 2025.01.05-1.21.4 (throws error) Caused by: java.lang.NoSuchMethodError: 'int java.util.List.pSize()' 	at TRANSFORMER/minecraft@1.21.4/net.minecraft.SystemReport.lambda$new$3(SystemReport.java:60) Caused by: java.lang.reflect.InvocationTargetException